let p = Promise.resolve()
.then(()=>{
    setTimeout(()=>{
        console.log('1')
    },1000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('2')
    },2000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('3')
    },3000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('4')
    },4000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('5')
    },5000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('6')
    },6000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('7')
    },7000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('8')
    },8000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('9')
    },9000)
})
.then(()=>{
    setTimeout(()=>{
        console.log('10')
    },10000)
})